"""Public exports for active V1 domain schemas."""

from ai_career_navigator.domain.analysis import (
    BridgeRoleAssessment,
    GapItem,
    RequirementComparison,
    RoleAssessment,
    TimelineAssessment,
)
from ai_career_navigator.domain.candidate import CandidateProfile, CareerGoal, EvidenceItem
from ai_career_navigator.domain.enums import (
    ApprovalStatus,
    BridgeOutcome,
    CandidateAccessibility,
    CareerStage,
    ComparisonScope,
    ConfidenceLevel,
    EmployerDiversity,
    EvidenceConfirmationStatus,
    EvidenceMaturity,
    FunctionalOverlap,
    GapCategory,
    GapSeverity,
    GeographyScope,
    GoalType,
    MarketBreadth,
    MarketConcentration,
    MatchType,
    MaturityAlignment,
    MilestoneStatus,
    MilestoneType,
    OpportunityAvailability,
    OwnershipAlignment,
    PartialMatchSubtype,
    PathType,
    PlanStatus,
    ProductionContextDifference,
    RequirementCategory,
    RequirementFrequency,
    RequirementStatementType,
    ScopeAlignment,
    TimelineClassification,
)
from ai_career_navigator.domain.market import (
    CurrentMarketSnapshot,
    JobPosting,
    RoleRequirement,
    SourceRecord,
)
from ai_career_navigator.domain.planning import CareerPlan, PlanMilestone

__all__ = [
    "ApprovalStatus",
    "BridgeOutcome",
    "BridgeRoleAssessment",
    "CandidateAccessibility",
    "CandidateProfile",
    "CareerGoal",
    "CareerPlan",
    "CareerStage",
    "ConfidenceLevel",
    "ComparisonScope",
    "CurrentMarketSnapshot",
    "EvidenceConfirmationStatus",
    "EvidenceItem",
    "EvidenceMaturity",
    "FunctionalOverlap",
    "EmployerDiversity",
    "GapCategory",
    "GapItem",
    "GapSeverity",
    "GeographyScope",
    "GoalType",
    "JobPosting",
    "MarketBreadth",
    "MarketConcentration",
    "MatchType",
    "MaturityAlignment",
    "MilestoneStatus",
    "MilestoneType",
    "PathType",
    "OpportunityAvailability",
    "OwnershipAlignment",
    "PartialMatchSubtype",
    "PlanMilestone",
    "PlanStatus",
    "RequirementCategory",
    "RequirementComparison",
    "RequirementFrequency",
    "RequirementStatementType",
    "ProductionContextDifference",
    "RoleAssessment",
    "RoleRequirement",
    "ScopeAlignment",
    "SourceRecord",
    "TimelineAssessment",
    "TimelineClassification",
]
