"""Bounded classifications used by active V1 domain models."""

from enum import StrEnum


class CareerStage(StrEnum):
    STUDENT = "STUDENT"
    RECENT_GRADUATE = "RECENT_GRADUATE"
    EARLY_CAREER = "EARLY_CAREER"
    MID_CAREER = "MID_CAREER"
    SENIOR_INDIVIDUAL_CONTRIBUTOR = "SENIOR_INDIVIDUAL_CONTRIBUTOR"
    LEADERSHIP_MANAGEMENT = "LEADERSHIP_MANAGEMENT"
    CAREER_RETURNER = "CAREER_RETURNER"
    OPEN_OTHER = "OPEN_OTHER"


class EvidenceMaturity(StrEnum):
    EXPOSURE = "EXPOSURE"
    DEMONSTRATED = "DEMONSTRATED"
    APPLIED = "APPLIED"
    PRODUCTION = "PRODUCTION"
    LEADERSHIP = "LEADERSHIP"


class EvidenceConfirmationStatus(StrEnum):
    EXPLICIT = "EXPLICIT"
    INFERRED_PENDING = "INFERRED_PENDING"
    CONFIRMED_INFERENCE = "CONFIRMED_INFERENCE"
    REJECTED_INFERENCE = "REJECTED_INFERENCE"


class GoalType(StrEnum):
    CAREER_EXPLORATION = "CAREER_EXPLORATION"
    CURRENT_MARKET_ANALYSIS = "CURRENT_MARKET_ANALYSIS"
    ROLE_TRANSITION = "ROLE_TRANSITION"
    TARGET_CAREER_PATH = "TARGET_CAREER_PATH"
    LEADERSHIP_PROGRESSION = "LEADERSHIP_PROGRESSION"
    CAREER_REASSESSMENT = "CAREER_REASSESSMENT"


class GeographyScope(StrEnum):
    STRICT_CITY = "STRICT_CITY"
    METRO_AREA = "METRO_AREA"
    PROVINCE = "PROVINCE"
    COUNTRY = "COUNTRY"
    COUNTRY_REMOTE = "COUNTRY_REMOTE"


class MatchType(StrEnum):
    DIRECT_MATCH = "DIRECT_MATCH"
    TRANSFERABLE_MATCH = "TRANSFERABLE_MATCH"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    NO_CONFIRMED_MATCH = "NO_CONFIRMED_MATCH"


class FunctionalOverlap(StrEnum):
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    NONE = "NONE"


class OwnershipAlignment(StrEnum):
    ALIGNED = "ALIGNED"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ScopeAlignment(StrEnum):
    ALIGNED = "ALIGNED"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"


class MaturityAlignment(StrEnum):
    ALIGNED = "ALIGNED"
    BELOW_TARGET = "BELOW_TARGET"
    UNKNOWN = "UNKNOWN"


class ProductionContextDifference(StrEnum):
    NONE = "NONE"
    PROJECT_TO_PRODUCTION = "PROJECT_TO_PRODUCTION"
    LIMITED_PRODUCTION_DEPTH = "LIMITED_PRODUCTION_DEPTH"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class PartialMatchSubtype(StrEnum):
    CAPABILITY_PRESENT_MATURITY_GAP = "CAPABILITY_PRESENT_MATURITY_GAP"
    ADJACENT_CAPABILITY_PARTIAL = "ADJACENT_CAPABILITY_PARTIAL"
    OWNERSHIP_OR_SCOPE_GAP = "OWNERSHIP_OR_SCOPE_GAP"


class ComparisonScope(StrEnum):
    EXACT_TARGET = "EXACT_TARGET"
    TARGET_VARIANT = "TARGET_VARIANT"
    RELATED_TITLE = "RELATED_TITLE"
    # Retained for checkpoint and fixture compatibility. New comparisons use RELATED_TITLE.
    COMBINED_RELATED = "COMBINED_RELATED"


class GapCategory(StrEnum):
    SKILL = "SKILL"
    EXPERIENCE = "EXPERIENCE"
    LEADERSHIP_SCOPE = "LEADERSHIP_SCOPE"
    EVIDENCE = "EVIDENCE"
    CREDENTIAL_PREREQUISITE = "CREDENTIAL_PREREQUISITE"


class GapSeverity(StrEnum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    BLOCKING = "BLOCKING"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class RequirementFrequency(StrEnum):
    COMMON = "COMMON"
    FREQUENT = "FREQUENT"
    OCCASIONAL = "OCCASIONAL"
    RARE = "RARE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class CandidateAccessibility(StrEnum):
    APPLY_NOW = "APPLY_NOW"
    APPLY_SELECTIVELY = "APPLY_SELECTIVELY"
    NEAR_TERM_TARGET = "NEAR_TERM_TARGET"
    ASPIRATIONAL = "ASPIRATIONAL"
    POOR_FIT = "POOR_FIT"
    INSUFFICIENT_CANDIDATE_EVIDENCE = "INSUFFICIENT_CANDIDATE_EVIDENCE"


class BridgeOutcome(StrEnum):
    NO_BRIDGE_REQUIRED = "NO_BRIDGE_REQUIRED"
    RECOMMENDED_BRIDGE = "RECOMMENDED_BRIDGE"
    MULTIPLE_PLAUSIBLE_BRIDGES = "MULTIPLE_PLAUSIBLE_BRIDGES"
    NO_VALID_BRIDGE_ROLE = "NO_VALID_BRIDGE_ROLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class TimelineClassification(StrEnum):
    NO_FIXED_TIMELINE = "NO_FIXED_TIMELINE"
    REALISTIC = "REALISTIC"
    AGGRESSIVE_BUT_PLAUSIBLE = "AGGRESSIVE_BUT_PLAUSIBLE"
    UNLIKELY_WITHOUT_INTERMEDIATE_ROLE = "UNLIKELY_WITHOUT_INTERMEDIATE_ROLE"
    UNSUPPORTED_INSUFFICIENT_EVIDENCE = "UNSUPPORTED_INSUFFICIENT_EVIDENCE"


class ConfidenceLevel(StrEnum):
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class ApprovalStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class PlanStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"


class PathType(StrEnum):
    DIRECT = "DIRECT"
    DEVELOPMENT = "DEVELOPMENT"
    BRIDGE = "BRIDGE"
    MULTIPLE_PATHS = "MULTIPLE_PATHS"
    EXPLORATION = "EXPLORATION"
    NO_CREDIBLE_PATH = "NO_CREDIBLE_PATH"


class MilestoneType(StrEnum):
    SKILL = "SKILL"
    EXPERIENCE = "EXPERIENCE"
    PROJECT = "PROJECT"
    LEADERSHIP_SCOPE = "LEADERSHIP_SCOPE"
    EVIDENCE = "EVIDENCE"
    MARKET_ACTION = "MARKET_ACTION"
    APPLICATION_READINESS = "APPLICATION_READINESS"
    REASSESSMENT = "REASSESSMENT"


class RequirementCategory(StrEnum):
    TECHNICAL = "TECHNICAL"
    DOMAIN = "DOMAIN"
    EXPERIENCE = "EXPERIENCE"
    EDUCATION = "EDUCATION"
    CREDENTIAL = "CREDENTIAL"
    LEADERSHIP = "LEADERSHIP"
    SCOPE = "SCOPE"
    COMMUNICATION = "COMMUNICATION"
    LOCATION = "LOCATION"
    WORK_AUTHORIZATION = "WORK_AUTHORIZATION"
    LANGUAGE = "LANGUAGE"
    OTHER = "OTHER"


class RequirementStatementType(StrEnum):
    """Source-grounded meaning of one extracted posting statement."""

    ROLE_RESPONSIBILITY = "ROLE_RESPONSIBILITY"
    HIRING_CAPABILITY = "HIRING_CAPABILITY"
    PREREQUISITE = "PREREQUISITE"
    PREFERENCE = "PREFERENCE"
    METADATA_NON_REQUIREMENT = "METADATA_NON_REQUIREMENT"


class MarketBreadth(StrEnum):
    """Legacy compatibility enum; not used by the active V1 market snapshot."""

    BROAD = "BROAD"
    MODERATE = "MODERATE"
    NICHE = "NICHE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class OpportunityAvailability(StrEnum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    LIMITED = "LIMITED"
    SPARSE = "SPARSE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class EmployerDiversity(StrEnum):
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class MarketConcentration(StrEnum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class MilestoneStatus(StrEnum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    DEFERRED = "DEFERRED"
    CANCELLED = "CANCELLED"
